name: Pre-release
run-name: "versioning: ${{ inputs.workspace }}/${{ inputs.path }}"
env:
  GITHUB_TOKEN: ${{ github.token }}
on:
  workflow_dispatch:
    inputs:
      workspace:
        description: "Choose a workspace"
        required: true
        type: choice
        options:
          - apps
          - packages
      type:
        description: "Choose a release version type"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
      path:
        description: "Need a release path directory"
        type: string
        required: true
      pull_request_url:
        description: "Include pull request url"
        type: string
        required: true
permissions: write-all
jobs:
  tagging:
    runs-on: ubuntu-latest
    env:
      PULL_REQUEST_URL: ${{ github.event.inputs.pull_request_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
      
      - name: Set current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY-MM-DD"

      - run: echo "BASE_VERSION=$(git rev-parse HEAD)" >> "$GITHUB_ENV"

      - run: gh auth setup-git

      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - run: ./scripts/versioning.sh --type=${{ github.event.inputs.type }} --workspace=${{ github.event.inputs.workspace }} --path=${{ github.event.inputs.path }}