name: Release
run-name: "release: ${{ inputs.tag }} ${{ inputs.ref }}"
env:
  GITHUB_TOKEN: ${{ github.token }}
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag"
        required: true
      ref:
        description: "released ref (branch, tag, or SHA)"
        required: false
        default: ""
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      
      - name: Set current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY-MM-DD"

      - run: echo "BASE_VERSION=$(git rev-parse HEAD)" >> "$GITHUB_ENV"

      - run: gh auth setup-git

      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - run: git tag "${{github.event.inputs.tag}}"
      - run: git push origin "${{github.event.inputs.tag}}"

      - run: |
          note_template='[${{github.event.inputs.tag}}](https://github.com/itsferdiardiansa/Github/compare/${{github.event.inputs.tag}}...${{github.event.inputs.tag}}) | [Pull Requests](https://github.com/itsferdiardiansa/Github/pulls?q=is%3Apr+is%3Aclosed) ${{ steps.date.outputs.time }}'
          gh release create "${{github.event.inputs.tag}}" -p --title "${{github.event.inputs.tag}}" -n "${note_template//BASE_REVISION/$BASE_REVISION}"