name: Release
run-name: "release: ${{ inputs.workspace }}/${{ inputs.path }}"
env:
  GITHUB_TOKEN: ${{ github.token }}
on:
  workflow_dispatch:
    inputs:
      workspace:
        description: "Choose a workspace"
        required: true
        type: choice
        options:
          - apps
          - packages
      type:
        description: "Choose a release version type"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
      path:
        description: "Need a release path directory"
        type: string
        required: true
      commit_tag:
        description: "Need a commit tag"
        type: string
        required: true
permissions: write-all
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      COMMIT_TAG: ${{ github.event.inputs.commit_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
      
      - name: Set current date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY-MM-DD"

      - run: echo "BASE_VERSION=$(git rev-parse HEAD)" >> "$GITHUB_ENV"

      - run: gh auth setup-git

      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # - run: git tag "${{github.event.inputs.tag}}"
      # - run: git push origin "${{github.event.inputs.tag}}"

      - run: ./scripts/release.sh --type=${{ github.event.inputs.type }} --workspace=${{ github.event.inputs.workspace }} --path=${{ github.event.inputs.path }}

      # - run: |
      #     note_template='Release v[${{github.event.inputs.tag}}](https://github.com/itsferdiardiansa/Github/compare/${{github.event.inputs.tag}}...${{github.event.inputs.tag}}) | [Pull Requests](https://github.com/itsferdiardiansa/Github/pulls?q=is%3Apr+is%3Aclosed) ${{ steps.date.outputs.time }}'
      #     gh release create "${{github.event.inputs.tag}}" -p --title "${{github.event.inputs.tag}}" -n "${note_template//BASE_REVISION/$BASE_REVISION}"