name: Create a pull request
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
permissions:
  contents: write
  pull-request: write
jobs:
  create-pr-branch:
    runs: ubuntu-latest
    steps:
      - run: echo ${{ inputs.version }}
